"""Ajout de alias dans la table organization

Revision ID: 1f44cf514154
Revises: 5cc212f12473
Create Date: 2026-05-02 14:48:18.045927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f44cf514154'
down_revision: Union[str, Sequence[str], None] = '5cc212f12473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('alias', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'alias')
    # ### end Alembic commands ###
